<?php if ($this->pageCount): ?>
<div class="col-sm-5">
	<div class="dataTables_info" id="example2_info" role="status" aria-live="polite">
		Showing <?php echo $this->firstItemNumber; ?> to <?php echo $this->lastItemNumber; ?> of <?php echo $this->totalItemCount; ?> entries
	</div>
</div>
<div class="col-sm-7">
	<ul class="pagination">
		<!-- Previous page link -->
             <?php if (isset($this->previous)): ?>
                 <li>
                 	<a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>">
						Previous
					</a>
				</li>
             <?php else: ?>
                 <li class="disabled"><a href="#"> Previous </a></li>
             <?php endif; ?>

             <!-- Numbered page links -->
             <?php foreach ($this->pagesInRange as $page): ?>
                 <?php if ($page != $this->current): ?>
                     <li><a href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>">
                             <?php echo $page; ?>
                         </a>
                     </li>
                 <?php else: ?>
                     <li class="active"><a href="#"><?php echo $page; ?></a></li>
                 <?php endif; ?>
             <?php endforeach; ?>

             <!-- Next page link -->
             <?php if (isset($this->next)): ?>
                <li>
                	<a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>">
						Next
					</a>
				</li>
             <?php else: ?>
                 <li class="disabled"><a href="#"> Next </a></li>
             <?php endif; ?>
         </ul>
</div>
<?php endif; ?>