<?php
$title = 'Add new album';
$this->headTitle($title);
?>

<?php
$form->setAttribute(
    'action',
    $this->url('album', array('action' => 'add'))
);
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<div class="col-md-6">
	<div class="box box-info">
		<div class="box-header with-border">
			<h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
		</div>
		<!-- /.box-header -->
		<!-- form start -->
		<?php echo $this->form()->openTag($form); ?>
			<div class="box-body">
				<div class="form-group">
					<label for="inputEmail3" class="col-sm-2 control-label">Title</label>
					<div class="col-sm-10">
						<?php echo $this->formRow($form->get('title')); ?>
					</div>
				</div>
				<div class="form-group">
					<label for="inputPassword3" class="col-sm-2 control-label">Artist</label>
					<div class="col-sm-10">
						<?php echo $this->formRow($form->get('artist')); ?>
					</div>
				</div>
			</div>
			<!-- /.box-body -->
			<div class="box-footer">
				<a href="<?php echo $this->url('album') ?>">
					<button type="button" class="btn btn-default"><i class="fa fa-close"></i> Cancel</button>
				</a>
				<button type="submit" class="btn btn-info pull-right"><i class="fa fa-save"></i> Save</button>
			</div>
			<!-- /.box-footer -->
			<?php echo $this->formHidden($form->get('id')); ?>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>