<?php
    $title = 'My albums';
    $this->headTitle($title);
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
				<a href="<?php echo $this->url('album', array('action' => 'add')); ?>">
					<button type="button" class="btn btn-info btn-sm pull-right"><i class="fa fa-plus"></i> Add new</button>
				</a>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				<div id="example2_wrapper"
					class="dataTables_wrapper form-inline dt-bootstrap">
					<div class="row">
						<div class="col-sm-6"></div>
						<div class="col-sm-6"></div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<table id="example2"
								class="table table-bordered table-hover dataTable" role="grid"
								aria-describedby="example2_info">
								<thead>
									<tr role="row">
                                        <th>Title</th>
                                        <th>Artist</th>
                                        <th>&nbsp;</th>
									</tr>
								</thead>
								<tbody>
									<?php foreach ($this->paginator as $key => $album): ?>
                                    <tr role="row" class="<?php echo ($key % 2 == 0) ? 'even' : 'odd';  ?>">
                                        <td><?php echo $this->escapeHtml($album->title);?></td>
                                        <td><?php echo $this->escapeHtml($album->artist);?></td>
                                    	<td class="col-sm-3">
                                    		<div class="col-sm-6">
                                    			<a href="<?php echo $this->url('album', array('action' => 'edit', 'id' => $album->id)); ?>">
                                    				<button type="button" class="btn btn-block btn-primary btn-sm"><i class="fa fa-edit"></i> Edit</button>
                                    			</a>
                                			</div>
                                    		<div class="col-sm-6">
                                    			<a href="<?php echo $this->url('album', array('action' => 'delete', 'id' => $album->id)); ?>">
                                    				<button type="button" class="btn btn-block btn-danger btn-sm"><i class="fa fa-trash"></i> Delete</button>
                                				</a>
                                			</div>
                                        </td>
									</tr>
									<?php endforeach; ?>
								</tbody>
							</table>
						</div>
					</div>
					<div class="row">
						<?php
                            echo $this->paginationControl(
                                // the paginator object
                                $this->paginator, 
                                // the scrolling style
                                'sliding', 
                                // the partial to use to render the control
                                'partial/paginator.phtml', 
                                // the route to link to when a user clicks a control link
                                array(
                                    'route' => 'album'
                                )
                            );
                        ?>
					</div>
				</div>
			</div>
			<!-- /.box-body -->
		</div>
		<!-- /.box -->
	</div>
	<!-- /.col -->
</div>